### ISSUE TITLE
Create GitHub Page

### ISSUE THREAD

**Issue by April6804** [Suad28d/Mixtape#2]
Are you able to create a GitHub Pages link?
Go to your settings and scroll down to GitHub Pages. 
Select a source, the master branch, or whatever branch you use,  and click save.

**Comment by Suad28d** [comment]
Once I do that step, do i go under packages to "Publish your first package?" or does it just link with the Mixtape on it's own?
Thank you.

**Comment by April6804** [comment]
I'm not sure what you mean. You will go to your GitHub Mixtape and click "Settings" then scroll down to GitHub Pages.
Select a source, the master branch, or whatever branch you use, and click save.
Then copy your link and put it in your README.
